name: airquality
channels:
  - bioconda
  - conda-forge
dependencies:
  - Jupyter
  - r-irkernel
  - r-recommended
  - r-devtools=2.4.3
  - r-base=4.1.2
  - r-tidyverse=1.3.1
  - r-leaflet=2.1.0
  - r-protolite=2.1
  - r-geojsonio=0.9.4
  - r-rmapshaper=0.4.5
  - r-rgdal=1.5_28
  - r-rlang=0.4.12
  - r-slippymath=0.3.1
  - r-tidyselect=1.1.1  
  - r-maps=3.4.0  
  - r-jpeg=0.1-9  
  - r-terra=1.5-21 
  - r-dplyr=1.0.7  
  - r-zoo=1.8-9  
  - r-units=0.8-0  
  - r-jqr=1.2.3  
  - r-rgeos=0.5-9  
  - r-V8=4.1.0  
  - r-sf=1.0_6  
  - r-waldo=0.3.1  
  - r-desc=1.4.0  
  - r-raster=3.5-15 
  - r-plyr=1.8.6  
  - r-hexbin=1.28.2 
  - r-mapproj=1.2.8  
  - r-latticeExtra=0.6-29 
  - r-bitops=1.0-7  
  - r-rjson=0.2.21 
  - r-RgoogleMaps=1.4.5.3
  - r-xts=0.12.1 
  - r-reshape2=1.4.4  
  - r-openair=2.8-6  
  - r-ggmap=3.0.0  
  - r-geosphere=1.5-14 
  - r-dygraphs=1.1.1.6
