#!/bin/bash

# Stop on fail!
set -e

# Read in packages
Rscript -e "library(withr)"
Rscript -e "library(devtools)"

# Install GitHub dependencies
Rscript -e "withr::with_libpaths(new = '/srv/conda/envs/notebook/lib/R/library', devtools::install_version('MazamaSpatialUtils', '0.7.6'))"
Rscript -e "withr::with_libpaths(new = '/srv/conda/envs/notebook/lib/R/library', devtools::install_version('PWFSLSmoke', '1.2.117'))"
